import React from "react";
import { prisma } from "@/lib/prisma";
import { auth } from "@/auth";
import { redirect } from "next/navigation";
import { GenerationsClient } from "./GenerationsClient";

export const revalidate = 0;

export default async function GenerationsPage() {
  const session = await auth();
  if (session?.user?.role !== "ADMIN") {
    redirect("/nextjs-app/pages");
  }

  const generations = await prisma.aIGeneration.findMany({
    orderBy: { createdAt: "desc" },
    include: {
      user: true,
      product: true,
    },
  });

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="text-2xl font-serif font-bold text-white">AI Studio Generations</h1>
        <p className="text-sm text-neutral-400 mt-1">
          Monitor all mosaic designs generated by users.
        </p>
      </div>

      <GenerationsClient initialGenerations={generations} />
    </div>
  );
}
